[Interface]
Address = 10.0.0.4/24
PrivateKey = <Private Key of client>
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = <Public Key of server>
Endpoint = 70.34.242.173:51820 # Server address
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 30

