[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = <Private Key of server>
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE;
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp1s0 -j MASQUERADE;

# IVFedora
[Peer]
PublicKey = DNhodC0jQ2HDz6efXkrSXgQ95I2IdOqctGLq3uu7ZA8=
AllowedIPs = 10.0.0.2/32

# Burchik
[Peer]
PublicKey = UD/bZu5CzNuua4iEmgpO+09zKN7fOvdI46wibpybm3M=
AllowedIPs = 10.0.0.3/32

# IV devices
[Peer]
PublicKey = sHJQbRrFvqBgd01Er6ELav3amwk2sBJs6gOjQaRq6AI=
AllowedIPs = 10.0.0.4/32

# Guest
[Peer]
PublicKey = 9Ax7nw77/nzq+PDhBTvKmMU5WvZXIj2OekhQbPhlqVc=
AllowedIPs = 10.0.0.5/32

