#!/bin/zsh

alias l="ls"
alias ll="ls -al"
alias v="vim"
alias vv="nvim"
alias g="git"
alias gs="git status"
alias gc="git commit -m"
alias gl="git log"
alias glast="git log -1 HEAD"
alias gpull="git pull"
alias gp="git push"
alias gpf="git push -f"
alias ga="git add"
alias gr="git restore"
alias gd="git checkout"
alias gamend="git commit --amend --no-edit"
alias tc="tmux new -s"
alias ta="tmux attach -t"
alias tq="tmux kill-session -t"
alias td="tmux detach -s"
alias tl="tmux ls"

