local opts = { noremap = true, silent = true, expr = false }

return {
  { m = 'n', k = '+', c = '<C-a>', o = opts },
  { m = 'n', k = '_', c = '<C-x>', o = opts },
  { m = 'n', k = '<Leader>p', c = '"0p', o = opts },
  { m = 'v', k = '<Leader>p', c = '"0p', o = opts },
  { m = 'n', k = '<C-a>', c = 'gg<S-v>G', o = opts },
  { m = 'n', k = 'st', c = ':tabedit<Return>', o = opts },
  { m = 'n', k = 'sh', c = ':split<Return>', o = opts },
  { m = 'n', k = 'sv', c = ':vsplit<Return>', o = opts },
  { m = 'n', k = '<Leader>j', c = '<C-w>j', o = opts },
  { m = 'n', k = '<Leader>k', c = '<C-w>k', o = opts },
  { m = 'n', k = '<Leader>h', c = '<C-w>h', o = opts },
  { m = 'n', k = '<Leader>l', c = '<C-w>l', o = opts },
  { m = 'n', k = '<Leader><left>', c = '20<C-w><', o = opts },
  { m = 'n', k = '<Leader><right>', c = '20<C-w>>', o = opts },
  { m = 'n', k = '<Leader><up>', c = '5<C-w>+', o = opts },
  { m = 'n', k = '<Leader><down>', c = '5<C-w>-', o = opts },
  { m = 'n', k = '<Esc>', c = ':noh<Return>', o = opts },
  { m = 'n', k = '<Leader>z', c = ':set spell<Return>', o = opts },
  { m = 'n', k = '<Leader>Z', c = ':set nospell<Return>', o = opts },
  { m = 'n', k = '<Leader>w', c = ':wa<Return>', o = opts },
  { m = 'n', k = '<Leader>q', c = ':wq<Return>', o = opts },
  { m = 'n', k = '<Leader>[', c = 'gT', o = opts },
  { m = 'n', k = '<Leader>]', c = 'gt', o = opts },
  { m = 'n', k = '<Leader>.', c = ':tabm +1<Return>', o = opts },
  { m = 'n', k = '<Leader>,', c = ':tabm -1<Return>', o = opts },
  { m = 'n', k = '<Leader>/', c = ':Lazy<Return>', o = opts },
  { m = 'n', k = '<Leader>t', c = ':term<Return>', o = opts },
  { m = 't', k = '<Esc>', c = '<C-\\><C-n>', o = opts },
}

